// StockData.cs (updated)
using UnityEngine;
using System.Collections.Generic;

[CreateAssetMenu(fileName = "New Stock", menuName = "Trading/Stock Data")]
public class StockData : ScriptableObject
{
    [Header("Base")]
    public string stockName = "STOCK";

    [Header("Price Data")]
    public List<int> priceHistory = new List<int>(); // Generated by TradingDataGenerator
    public int currentPrice;
    
    public float basePrice = 100f;
    public float volatility = 0.02f;        // σ
    public float jumpProbability = 0.05f;   // λ
    public float minJumpSize = 0.1f;        // ξ_min
    public float maxJumpSize = 0.4f;        // ξ_max


    public void InitializePriceHistory(int pointCount)
    {
        priceHistory = TradingDataGenerator.GeneratePriceData(
            pointCount, basePrice, volatility, jumpProbability, minJumpSize, maxJumpSize);
    }

    public void AddNewPrice()
    {
        if (priceHistory.Count == 0)
        {
            InitializePriceHistory(1);
            return;
        }

        float lastPrice = priceHistory[priceHistory.Count - 1];
        
        // 1. GBM MOVE
        float z = SampleNormal(0f, 1f);
        float priceChange = lastPrice * volatility * z;

        // 2. JUMP (5% chance)
        if (Random.value < jumpProbability)
        {
            float jumpSize = Random.Range(minJumpSize, maxJumpSize);
            if (Random.value < 0.5f) jumpSize *= -1f;
            priceChange = lastPrice * jumpSize;
        }

        // 3. UPDATE
        float newPrice = lastPrice + priceChange;
        newPrice = Mathf.Max(newPrice, 1f);

        priceHistory.Add(Mathf.RoundToInt(newPrice));
        if (priceHistory.Count > 100) priceHistory.RemoveAt(0);
    }

    // Reuse normal sampler
    private static float SampleNormal(float mean, float stdDev)
    {
        float u1 = 1.0f - Random.value;
        float u2 = 1.0f - Random.value;
        float randStdNormal = Mathf.Sqrt(-2.0f * Mathf.Log(u1)) * Mathf.Sin(2.0f * Mathf.PI * u2);
        return mean + stdDev * randStdNormal;
    }
    public void UpdateCurrentPrice(int newPrice)
    {
        currentPrice = newPrice;

    }
    public int GetCurrentPrice()
    {
        return currentPrice;
    }
}